Bundler.require *[:default, 'test']

require 'sidekiq/api'

Dir["./lib/*.rb"].each { |f| require f  }

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
def app
  SidekiqMonitoring.new
end

RSpec.configure do |config|
  config.include Rack::Test::Methods
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # NOTE: should not use redis while testing
  Sidekiq.redis = ConnectionPool.new(size: 5) { $REDIS = MockRedis.new }
end
